'use strict';
(()=>{
 const $=id=>document.getElementById(id),canvas=$('scene'),hud=$('overlay'),hc=hud.getContext('2d'),pc=$('pfd').getContext('2d');
 const app={active:false,paused:true,view:0,clock:0,light:'day',sound:false,lookX:0,lookY:0,zoom:1,sensitivity:.8,invert:false,menuType:'light',fps:60,frames:0,lastUI:0,helpFrom:null};
 const input={pitch:0,roll:0,yaw:0,brake:false},touch={pitch:0,roll:0,left:false,right:false,brake:false},keys=new Set();let mission=null;let engine,world,models,flight,cam,eyeSmooth=null,accum=0,toastUntil=0,propAngle=0,audio=null;
 let prefs={};try{prefs=JSON.parse(localStorage.getItem('cloudline.preferences')||'{}')}catch(_){}
 for(let [id,key]of [['aircraftSelect','aircraft'],['modeSelect','mode'],['weatherSelect','weather'],['timeSelect','light']])if(prefs[key]&&[...$(id).options].some(o=>o.value===prefs[key]))$(id).value=prefs[key];
 app.menuType=$('aircraftSelect').value;app.light=$('timeSelect').value;
 function toast(text,duration=2600){$('toast').textContent=text;$('toast').classList.remove('off');toastUntil=performance.now()+duration}
 function fatal(text){$('fatalText').textContent=text;$('fatal').classList.remove('hidden');$('loading').classList.add('hidden');if(app.active)app.paused=true}
 window.addEventListener('error',e=>{if(e.message&&e.message!=='Script error.')fatal('运行中出现错误：'+e.message)});
 document.addEventListener('graphicslost',()=>{clearInputs();fatal('图形上下文已被浏览器释放。请重新加载；再次进入后可在「系统」里选择省电画质。')});
 const styles={day:{sky:[.24,.53,.71],horizon:[.72,.83,.83],sun:M.norm([-.45,.76,.3]),night:0,fog:.000072},golden:{sky:[.32,.48,.57],horizon:[.89,.71,.51],sun:M.norm([-.6,.22,-.5]),night:0,fog:.00009},night:{sky:[.025,.055,.10],horizon:[.13,.21,.28],sun:M.norm([.2,.46,.3]),night:.88,fog:.000052}};
 function style(){let base=styles[app.light];return {...base,fog:base.fog*(flight&&flight.weather==='turbulent'?1.55:1)}}
 function resize(){let w=innerWidth,h=innerHeight;if(engine)engine.resize(w,h);const d=Math.min(devicePixelRatio||1,1.5);if(hud.width!==Math.round(w*d)||hud.height!==Math.round(h*d)){hud.width=Math.round(w*d);hud.height=Math.round(h*d);hc.setTransform(d,0,0,d,0,0)}eyeSmooth=null}
 addEventListener('resize',resize);
 function clearInputs(){stickPointer=null;throttlePointer=null;pan=null;keys.clear();Object.assign(touch,{pitch:0,roll:0,left:false,right:false,brake:false});Object.assign(input,{pitch:0,roll:0,yaw:0,brake:false});$('knob').style.transform='translate(0px,0px)';for(let el of document.querySelectorAll('.held'))el.classList.remove('on','held')}
 const modalIds=['pauseModal','systemsModal','helpModal','mapModal','resultModal'];
 function closeModals(){for(let id of modalIds)$(id).classList.add('hidden')}
 function openModal(id){clearInputs();app.paused=true;$(id).classList.remove('hidden');if(audio)audio.gain.gain.setTargetAtTime(.00001,audio.ctx.currentTime,.06)}
 function resume(){if(!app.active||flight.crashed)return;closeModals();app.paused=false;accum=0;eyeSmooth=null;if(audio&&audio.ctx.state==='suspended')audio.ctx.resume().catch(()=>{});updateUI()}
 function pause(){if(!app.active)return;if(app.paused&&!flight.crashed)resume();else if(!flight.crashed)openModal('pauseModal')}
 function switchScene(key){if(AirportScenes.key===key)return;disposeWorld();AirportScenes.select(key);world=World.build(engine);initMap();eyeSmooth=null;}
 function disposeWorld(){if(world)for(let m of Object.values(world))if(m&&m.b)engine.gl.deleteBuffer(m.b);}
 function routeTransfer(){if(!mission||!mission.transfer)return;clearInputs();const next=mission.transfer;disposeWorld();mission.configure(flight,next);world=World.build(engine);initMap();eyeSmooth=null;toast('场景切换 · '+mission.phaseName+'（游戏分段体验）',3600);}
 function start(type=$('aircraftSelect').value,mode=$('modeSelect').value){
  if(!engine||engine.lost)return;const routeMode=['bki_can','can_approach','can_taxi'].includes(mode);mission=routeMode?new RouteMission(mode):null;if(routeMode)type='a320';switchScene('island');flight=new Flight(type,routeMode?'runway':mode,$('weatherSelect').value,$('assistSelect').checked);app.light=$('timeSelect').value;app.active=true;app.paused=false;app.view=0;app.lookX=0;app.lookY=0;app.zoom=1;eyeSmooth=null;clearInputs();closeModals();accum=0;
  $('menu').classList.add('hidden');$('flightUI').classList.remove('hidden','cockpit');$('viewBtn').textContent='追尾';$('weatherLive').value=flight.weather;$('timeLive').value=app.light;$('assistToggle').checked=flight.assist;
  try{localStorage.setItem('cloudline.preferences',JSON.stringify({aircraft:type,mode,weather:flight.weather,light:app.light}))}catch(_){}
  toast(mode==='free'?'已在空中。左摇杆轻推试试，右滑杆调整动力。':mode==='landing'?'已对正跑道。保持绿色引导路径，接地后按住刹车。':'油门推满，达到提示速度后轻拉摇杆。',4500);
  if(mission)routeTransfer();$('routePanel').classList.toggle('hidden',!mission);$('flightUI').classList.toggle('route-active',!!mission);if(audio&&app.sound)audio.ctx.resume().catch(()=>{});updateUI();resize();
 }
 function hangar(){mission=null;switchScene('island');app.active=false;app.paused=true;clearInputs();closeModals();$('menu').classList.remove('hidden');$('flightUI').classList.add('hidden');app.menuType=$('aircraftSelect').value;eyeSmooth=null;toastUntil=0;$('toast').classList.add('off')}
 function restart(){if(flight)start(flight.type,flight.mode)}
 function cycleView(){app.view=(app.view+1)%4;app.lookX=0;app.lookY=0;app.zoom=1;eyeSmooth=null;$('viewBtn').textContent=['追尾','驾驶舱','翼侧','环绕'][app.view];$('flightUI').classList.toggle('cockpit',app.view===1);toast(['追尾视角','驾驶舱视角 · 拖动场景环顾','机翼观察视角','环绕视角 · 拖动场景调整'][app.view],1700)}
 $('startBtn').onclick=()=>start();$('modeSelect').onchange=()=>{if(['bki_can','can_approach','can_taxi'].includes($('modeSelect').value)){$('aircraftSelect').value='a320';app.menuType='a320';}};$('guideBtn').onclick=()=>{if(!mission||app.paused)return;mission.guide=!mission.guide;flight.ap.on=false;toast(mission.guide?'教学领航接管操纵；动摇杆可随时接回。':'已关闭教学领航');updateUI()};$('routeNext').onclick=()=>{if(mission&&!app.paused){mission.requestNext(flight);routeTransfer();updateUI();}};$('aircraftSelect').onchange=()=>{app.menuType=$('aircraftSelect').value;eyeSmooth=null};$('timeSelect').onchange=()=>app.light=$('timeSelect').value;
 $('pauseBtn').onclick=pause;$('resumeBtn').onclick=resume;$('restartBtn').onclick=restart;$('hangarBtn').onclick=hangar;$('viewBtn').onclick=cycleView;$('retryResult').onclick=restart;$('freeResult').onclick=()=>start(flight.type,'free');$('hangarResult').onclick=hangar;
 function flaps(){if(!flight||flight.crashed)return;flight.flaps=(flight.flaps+1)%4;toast('襟翼 '+flight.flaps+' / 3');updateUI()}
 $('flapsBtn').onclick=flaps;$('gearBtn').onclick=()=>{flight.setGear();updateUI()};$('apBtn').onclick=()=>{if(mission)mission.cancelGuide(flight);flight.toggleAP();updateUI()};
 // Pointer state is independent from keyboard state. Never overwrite active touch input.
 let stickPointer=null,stickRect=null;const stick=$('stick');
 function moveStick(x,y){let r=stickRect||stick.getBoundingClientRect(),dx=x-r.left-r.width/2,dy=y-r.top-r.height/2,max=r.width*.34,len=Math.hypot(dx,dy);if(len>max){dx*=max/len;dy*=max/len}let dead=v=>Math.abs(v)<.04?0:Math.sign(v)*(Math.abs(v)-.04)/.96;touch.roll=dead(M.clamp(dx/max,-1,1));touch.pitch=dead(M.clamp(dy/max,-1,1));$('knob').style.transform=`translate(${dx}px,${dy}px)`;stick.setAttribute('aria-valuetext',`俯仰 ${Math.round(touch.pitch*100)}，横滚 ${Math.round(touch.roll*100)}`)}
 stick.addEventListener('pointerdown',e=>{if(stickPointer!==null)return;e.preventDefault();stickPointer=e.pointerId;stickRect=stick.getBoundingClientRect();stick.setPointerCapture(e.pointerId);moveStick(e.clientX,e.clientY)});
 stick.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer){e.preventDefault();moveStick(e.clientX,e.clientY)}});
 function releaseStick(e){if(e.pointerId!==stickPointer)return;stickPointer=null;touch.pitch=0;touch.roll=0;$('knob').style.transform='translate(0px,0px)'}for(let name of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(name,releaseStick);
 let throttlePointer=null;const thr=$('throttle');function setPower(y){if(!flight)return;let r=thr.getBoundingClientRect();if(mission)mission.cancelGuide(flight);flight.power=M.clamp(1-(y-r.top-10)/(r.height-20),0,1);if(flight.ap.on){flight.ap.on=false;toast('手动调整油门，自动驾驶已断开')}updateUI()}
 thr.addEventListener('pointerdown',e=>{if(throttlePointer!==null)return;e.preventDefault();throttlePointer=e.pointerId;thr.setPointerCapture(e.pointerId);setPower(e.clientY)});thr.addEventListener('pointermove',e=>{if(e.pointerId===throttlePointer){e.preventDefault();setPower(e.clientY)}});for(let n of ['pointerup','pointercancel','lostpointercapture'])thr.addEventListener(n,e=>{if(e.pointerId===throttlePointer)throttlePointer=null});
 function held(id,key){let pointer=null,el=$(id);el.addEventListener('pointerdown',e=>{e.preventDefault();pointer=e.pointerId;el.setPointerCapture(e.pointerId);touch[key]=true;el.classList.add('on','held')});let up=e=>{if(e.pointerId!==pointer)return;pointer=null;touch[key]=false;el.classList.remove('on','held')};for(let n of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(n,up)}held('rudderL','left');held('rudderR','right');held('brakeBtn','brake');
 let pan=null;canvas.addEventListener('pointerdown',e=>{if(!app.active||app.paused)return;pan={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!pan||e.pointerId!==pan.id)return;app.lookX=M.clamp(app.lookX+(e.clientX-pan.x)*.008,-2.8,2.8);app.lookY=M.clamp(app.lookY+(e.clientY-pan.y)*.006,-.8,.8);pan.x=e.clientX;pan.y=e.clientY});for(let n of ['pointerup','pointercancel'])canvas.addEventListener(n,()=>{pan=null});canvas.addEventListener('dblclick',()=>{app.lookX=app.lookY=0});canvas.addEventListener('wheel',e=>{if(!app.active)return;e.preventDefault();app.zoom=M.clamp(app.zoom+e.deltaY*.0015,.6,2.3)},{passive:false});
 const usedKeys=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyS','KeyA','KeyD','KeyQ','KeyE','Space','Equal','Minus','NumpadAdd','NumpadSubtract','ShiftLeft','ShiftRight','ControlLeft','KeyP','KeyR','KeyV','KeyF','KeyG','KeyH','Escape'];
 addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(!app.active)return;if(usedKeys.includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyP'||e.code==='Escape'){pause();return}if(app.paused)return;if(e.code==='KeyV')cycleView();if(e.code==='KeyR')restart();if(e.code==='KeyF')flaps();if(e.code==='KeyG')flight.setGear();if(e.code==='KeyH')flight.toggleAP()});addEventListener('keyup',e=>keys.delete(e.code));
 addEventListener('blur',()=>{clearInputs();if(app.active&&!app.paused&&!flight.crashed)openModal('pauseModal')});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInputs();if(app.active&&!app.paused&&!flight.crashed)openModal('pauseModal')}});document.addEventListener('contextmenu',e=>{if(e.target.closest('#flightUI')||e.target===canvas)e.preventDefault()});
 function readInput(dt){const k=(...names)=>names.some(n=>keys.has(n))?1:0;input.pitch=M.clamp((touch.pitch*(app.invert?-1:1)+k('KeyS','ArrowDown')-k('KeyW','ArrowUp'))*app.sensitivity,-1,1);input.roll=M.clamp((touch.roll+k('KeyD','ArrowRight')-k('KeyA','ArrowLeft'))*app.sensitivity,-1,1);input.yaw=M.clamp((touch.right?1:0)-(touch.left?1:0)+k('KeyE')-k('KeyQ'),-1,1);input.brake=touch.brake||!!k('Space');let d=k('Equal','NumpadAdd','ShiftLeft','ShiftRight')-k('Minus','NumpadSubtract','ControlLeft');if(d){flight.power=M.clamp(flight.power+d*dt*.32,0,1);flight.ap.on=false}}
 function showHelp(from=null){app.helpFrom=from;openModal('helpModal')}$('menuHelp').onclick=()=>showHelp('menu');$('systemHelp').onclick=()=>showHelp('systems');$('closeHelp').onclick=()=>{$('helpModal').classList.add('hidden');if(app.helpFrom==='systems')return;if(app.active)resume()};
 function headingOffset(){return mission?World.profile.heading*DEG:0}
 function showSystems(){if(!app.active)return;openModal('systemsModal');$('engineBtn').textContent=flight.engine?'运转中':'已关闭';$('speedbrakeBtn').textContent=flight.speedbrake?'展开':'收起';$('apAlt').value=Math.round((flight.ap.on?flight.ap.alt:flight.p[1])*3.28084/100)*100;$('apHdg').value=Math.round((((flight.ap.on?flight.ap.heading:flight.yaw)+headingOffset())/DEG+360)%360);$('apSpeed').value=Math.round((flight.ap.on?flight.ap.speed:flight.ias)*1.94384);$('trimValue').textContent=(flight.trim/DEG).toFixed(1)+'°';$('weatherLive').value=flight.weather;$('timeLive').value=app.light;$('assistToggle').checked=flight.assist;}
 $('systemsBtn').onclick=showSystems;$('closeSystems').onclick=resume;$('engineBtn').onclick=()=>{flight.engine=!flight.engine;$('engineBtn').textContent=flight.engine?'运转中':'已关闭'};$('speedbrakeBtn').onclick=()=>{flight.speedbrake=!flight.speedbrake;$('speedbrakeBtn').textContent=flight.speedbrake?'展开':'收起'};
 $('trimDown').onclick=()=>{flight.trim=M.clamp(flight.trim-.005,-.10,.10);$('trimValue').textContent=(flight.trim/DEG).toFixed(1)+'°'};$('trimUp').onclick=()=>{flight.trim=M.clamp(flight.trim+.005,-.10,.10);$('trimValue').textContent=(flight.trim/DEG).toFixed(1)+'°'};
 $('assistToggle').onchange=e=>flight.assist=e.target.checked;$('invertToggle').onchange=e=>app.invert=e.target.checked;$('sensitivity').oninput=e=>app.sensitivity=Number(e.target.value);$('weatherLive').onchange=e=>flight.weather=e.target.value;$('timeLive').onchange=e=>app.light=e.target.value;$('quality').onchange=e=>{engine.quality=Number(e.target.value);resize()};
 $('apApply').onclick=()=>{if(flight.grounded){toast('自动驾驶需要在离地后使用');return}let a=Number($('apAlt').value),h=Number($('apHdg').value),v=Number($('apSpeed').value);if(![a,h,v].every(Number.isFinite)){toast('请填写有效的数字');return}flight.ap.on=true;flight.ap.alt=M.clamp(a,300,flight.type==='a320'?41000:20000)/3.28084;flight.ap.heading=wrapAngle(((h%360)+360)%360*DEG-headingOffset());flight.ap.speed=M.clamp(v,flight.type==='light'?60:140,flight.type==='light'?155:340)/1.94384;flight.ap.integral=flight.power;resume();toast('自动驾驶目标已应用')};
 $('returnBtn').onclick=()=>{if(flight.grounded){toast('离地后可设置返机场航向');return}flight.ap.on=true;flight.ap.alt=Math.max(flight.p[1],1500);flight.ap.heading=Math.atan2(-flight.p[0],-flight.p[2]);flight.ap.speed=flight.spec.cruise;flight.ap.integral=flight.power;resume();toast('已设定朝机场方向飞行。到达前需手动接管；不会自动降落。',4300)};
 $('fullscreenBtn').onclick=async()=>{try{if(document.fullscreenElement){await document.exitFullscreen();return}if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();try{await screen.orientation.lock('landscape')}catch(_){}}else toast('此浏览器不支持主动全屏，请手动横屏使用。',3500)}catch(_){toast('无法进入全屏，仍可继续在当前窗口玩。')}};
 function initAudio(){const C=window.AudioContext||window.webkitAudioContext;if(!C){toast('此浏览器不支持网页音效');return false}try{const ctx=new C(),gain=ctx.createGain(),low=ctx.createBiquadFilter(),osc=ctx.createOscillator(),sub=ctx.createOscillator(),mix=ctx.createGain();gain.gain.value=.00001;low.type='lowpass';low.frequency.value=400;osc.type='sawtooth';osc.frequency.value=70;sub.type='triangle';sub.frequency.value=36;mix.gain.value=.18;osc.connect(mix);sub.connect(mix);mix.connect(low);low.connect(gain);gain.connect(ctx.destination);osc.start();sub.start();audio={ctx,gain,low,osc,sub};return true}catch(_){toast('声音未能启动；游戏仍可静音运行');return false}}
 function toggleSound(){if(!audio&&!initAudio())return;app.sound=!app.sound;audio.ctx.resume().catch(()=>{});$('soundBtn').textContent=app.sound?'声音':'静音';$('soundSystems').textContent=app.sound?'开启':'关闭'}$('soundBtn').onclick=toggleSound;$('soundSystems').onclick=toggleSound;
 function soundUpdate(){if(!audio)return;const t=audio.ctx.currentTime,on=app.sound&&app.active&&!app.paused&&!flight.crashed;let volume=on?.028+flight.spool*.045:.00001;audio.gain.gain.setTargetAtTime(volume,t,.12);if(on){audio.osc.frequency.setTargetAtTime((flight.type!=='light'?52:38)+flight.spool*(flight.type!=='light'?90:57),t,.15);audio.sub.frequency.setTargetAtTime(26+flight.spool*24,t,.2);audio.low.frequency.setTargetAtTime(250+flight.spool*350,t,.2)}}
 const mapBase=document.createElement('canvas');mapBase.width=mapBase.height=200;let mb=mapBase.getContext('2d'),img=mb.createImageData(200,200),mapExtent=7500;
 function initMap(){for(let y=0;y<200;y++)for(let x=0;x<200;x++){let h=World.height((x/200-.5)*mapExtent*2,(.5-y/200)*mapExtent*2),c=h<0?[26,66,77]:h<35?[83,109,83]:h<350?[61+Math.round(h*.035),90+Math.round(h*.025),69]:[99+Math.min(28,h*.015),112+Math.min(28,h*.015),98];let i=(y*200+x)*4;img.data.set([...c,255],i)}mb.putImageData(img,0,0)}
 function drawMap(c,big=false){let ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.fillStyle='#153945';ctx.fillRect(0,0,w,h);const span=big?15000:8500,cx=big?0:flight.p[0]*.65,cz=big?0:flight.p[2]*.65,s=Math.min(w,h)/span;
  let X=x=>w/2+(x-cx)*s,Y=z=>h/2-(z-cz)*s;ctx.drawImage(mapBase,X(-mapExtent),Y(mapExtent),mapExtent*2*s,mapExtent*2*s);ctx.strokeStyle='#a4c8b21f';ctx.lineWidth=1;for(let x=-15000;x<=15000;x+=2000){ctx.beginPath();ctx.moveTo(X(x),0);ctx.lineTo(X(x),h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,Y(x));ctx.lineTo(w,Y(x));ctx.stroke()}
  ctx.strokeStyle='#f2e6b5';ctx.lineWidth=big?5:3;ctx.beginPath();ctx.moveTo(X(0),Y(-World.profile.length/2));ctx.lineTo(X(0),Y(World.profile.length/2));ctx.stroke();ctx.fillStyle='#e5ecd7';ctx.font=(big?'16':'15')+'px sans-serif';ctx.fillText(World.profile.runway.split(' / ')[0],X(0)+8,Y(-World.profile.length/2)+10);
  if(mission&&AirportScenes.key==='can'){ctx.strokeStyle='#ffdb80';ctx.lineWidth=3;ctx.beginPath();[[0,100],...mission.taxiPoints].forEach((p,i)=>i?ctx.lineTo(X(p[0]),Y(p[1])):ctx.moveTo(X(p[0]),Y(p[1])));ctx.stroke();ctx.fillStyle='#b8ffca';ctx.fillText('T3',X(245)+8,Y(-440));}
  if(flight.mode==='lesson'){ctx.strokeStyle='#abe1c39a';ctx.lineWidth=big?2:1.6;ctx.setLineDash([5,4]);ctx.beginPath();World.gates.forEach((g,i)=>i?ctx.lineTo(X(g.x),Y(g.z)):ctx.moveTo(X(g.x),Y(g.z)));ctx.stroke();ctx.setLineDash([]);World.gates.forEach((g,i)=>{ctx.fillStyle=i<flight.gate?'#607c70':i===flight.gate?'#e9c98f':'#b4dacf';ctx.beginPath();ctx.arc(X(g.x),Y(g.z),big?5:3,0,Math.PI*2);ctx.fill();if(big)ctx.fillText(i+1,X(g.x)+8,Y(g.z)-6)})}
  ctx.save();ctx.translate(X(flight.p[0]),Y(flight.p[2]));ctx.rotate(flight.yaw);ctx.fillStyle='#bbf3dd';ctx.strokeStyle='#072d32';ctx.lineWidth=1.5;let a=big?13:10;ctx.beginPath();ctx.moveTo(0,-a);ctx.lineTo(a*.6,a*.65);ctx.lineTo(0,a*.28);ctx.lineTo(-a*.6,a*.65);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.fillStyle='#cde4d8';ctx.font=(big?'17':'16')+'px sans-serif';ctx.fillText('N ↑',10,22);if(big){ctx.fillStyle='#b6cdc0';ctx.font='14px sans-serif';ctx.fillText(World.profile.name+' · 机场布局简化',16,h-18)}
 }
 $('mapBtn').onclick=()=>{$('mapModal').querySelector('h2').textContent=mission?'机场局部示意':'岛屿导航';openModal('mapModal');drawMap($('bigMap'),true);$('mapDetails').textContent=`距机场 ${(Math.hypot(flight.p[0],flight.p[2])/1852).toFixed(1)} 海里 · 当前海拔 ${Math.round(flight.p[1]*3.28084)} 英尺 · 地图上方为北。`};$('closeMap').onclick=resume;$('routeInfoBtn').onclick=()=>{$('mapModal').querySelector('h2').textContent='BKI → CAN T3 航线';openModal('mapModal');const c=$('bigMap'),g=c.getContext('2d'),w=c.width,h=c.height;g.fillStyle='#102d3b';g.fillRect(0,0,w,h);g.strokeStyle='#2d5260';g.lineWidth=1;for(let i=1;i<8;i++){g.beginPath();g.moveTo(i*w/8,0);g.lineTo(i*w/8,h);g.stroke();}let a=[w*.70,h*.79],b=[w*.34,h*.20];g.strokeStyle='#a6e3cd';g.lineWidth=3;g.setLineDash([10,7]);g.beginPath();g.moveTo(...a);g.quadraticCurveTo(w*.56,h*.50,...b);g.stroke();g.setLineDash([]);g.fillStyle='#def6e7';g.font='24px sans-serif';g.fillText('BKI · 亚庇',a[0]-40,a[1]+40);g.fillText('CAN · 广州 T3',b[0]-60,b[1]-25);g.font='18px sans-serif';g.fillText('南海 / SOUTH CHINA SEA',w*.16,h*.53);for(let p of [a,b]){g.beginPath();g.arc(...p,7,0,Math.PI*2);g.fill();}let t=mission.progress,x=(1-t)*a[0]+t*b[0],y=(1-t)*a[1]+t*b[1];g.fillStyle='#f5d28e';g.beginPath();g.arc(x,y,9,0,Math.PI*2);g.fill();g.font='14px sans-serif';g.fillText('大圆方向示意 · 非真实 ATC 航路或实时航迹',22,h-22);$('mapDetails').textContent='A320-216 / CFM56 · '+Math.round(ROUTE_DATA.distance/1000)+' km 机场间大圆距离（约）。此任务采用游戏化简化，以局部场景分段衔接，巡航航程加速推进。CAN 跑道与 SIM-T3 机位为场景设定，不代表实际当班跑道或登机口。';};
 function getCamera(){const portrait=innerHeight>innerWidth,aspect=innerWidth/innerHeight,fov=(portrait?76:62)*DEG;
  if(!app.active){let type=app.menuType,jet=type!=='light',p=[320,jet?335:235,-350],angle=-.42+Math.sin(app.clock*.06)*.08,scale=jet?2.8:1;let f=M.basis(angle,.035,-.08).f,eye=M.add(p,[19*scale,7*scale,20*scale]),target=M.add(p,[-(portrait?0:3)*scale,0,-2*scale]);app.preview={p,yaw:angle,pitch:.035,bank:-.08};return M.camera(eye,target,[0,1,0],(portrait?65:54)*DEG,aspect)}
  const f=flight,b=M.basis(f.yaw,f.pitch,f.bank),jet=f.type!=='light';let eye,target,up=[0,1,0];
  if(app.view===1){let local=jet?[0,2.75,13.0]:[0,1.52,.90];eye=M.add(f.p,M.add(M.mul(b.r,local[0]),M.add(M.mul(b.u,local[1]),M.mul(b.f,local[2]))));let look=M.norm(M.add(M.mul(b.f,Math.cos(app.lookX)),M.add(M.mul(b.r,Math.sin(app.lookX)),M.mul(b.u,-app.lookY))));target=M.add(eye,M.mul(look,100));up=b.u;eyeSmooth=null;return M.camera(eye,target,up,fov,aspect,.20)}
  if(app.view===0){let a=f.yaw+app.lookX,dist=(jet?64:23)*app.zoom;eye=M.add(f.p,[-Math.sin(a)*dist,(jet?17:7)+app.lookY*dist*.65,-Math.cos(a)*dist]);target=M.add(f.p,M.add(M.mul(b.f,jet?20:7),[0,jet?3:1.2,0]))}
  else if(app.view===2){eye=M.add(f.p,M.add(M.mul(b.r,(jet?29:10)*app.zoom),M.add(M.mul(b.f,-(jet?9:3)),[0,jet?4:2.5,0])));target=M.add(f.p,M.mul(b.f,jet?8:2));}
  else{let a=app.clock*.12+app.lookX,d=(jet?69:24)*app.zoom;eye=M.add(f.p,[Math.sin(a)*d,d*(.30+app.lookY),Math.cos(a)*d]);target=f.p.slice()}
  eye[1]=Math.max(eye[1],World.ground(eye[0],eye[2])+2);if(!eyeSmooth)eyeSmooth=eye;else eyeSmooth=M.add(eyeSmooth,M.mul(M.sub(eye,eyeSmooth),.12));return M.camera(eyeSmooth,target,up,fov,aspect,.8)
 }
 const localPoint=(p,b,a)=>M.add(p,M.add(M.mul(b.r,a[0]),M.add(M.mul(b.u,a[1]),M.mul(b.f,a[2]))));
 function drawPlane(type,p,yaw,pitch,bank,cockpit=false){const model=models[type],b=M.basis(yaw,pitch,bank),mat=M.model(p,yaw,pitch,bank),gear=app.active?flight.gearActual:1,flap=app.active?flight.flapActual:0;
  engine.draw(cockpit?model.cockpit:model.body,mat);if(!cockpit&&gear>.03)engine.draw(model.gear,M.matmul(mat,M.model([0,0,0],0,0,0,gear)));
  if(!cockpit)engine.draw(model.flaps,M.matmul(mat,M.model(type==='light'?[0,1.19,-.72]:[0,.08,-1.9],0,flap*.54)));
  if(type==='light')engine.draw(model.prop,M.matmul(mat,M.model([0,.35,4.05],0,0,propAngle)),0,app.active&&flight.spool>.2?.38:1);
  if(!cockpit){const span=type!=='light'?16.5:5.42;engine.draw(navLights.red,M.model(localPoint(p,b,[-span,type!=='light'?.58:1.38,-.2])) ,2);engine.draw(navLights.green,M.model(localPoint(p,b,[span,type!=='light'?.58:1.38,-.2])),2);if(Math.sin(app.clock*5)> .82)engine.draw(navLights.white,M.model(localPoint(p,b,[0,type!=='light'?8:2.22,type!=='light'?-16:-3.8])),2)}
 }
 let navLights;
 function render(){if(!engine||engine.lost)return;cam=getCamera();engine.begin(cam,app.clock,style());engine.draw(world.sea,undefined,1);engine.draw(world.terrain);engine.draw(world.airport,undefined,0,1,-1);engine.draw(world.markings,undefined,0,1,-5);engine.draw(world.structures);engine.draw(world.foliage);engine.draw(world.clouds);engine.draw(world.lights,undefined,2);
  if(app.active){if(flight.mode==='lesson')for(let i=flight.gate;i<Math.min(World.gates.length,flight.gate+3);i++){let g=World.gates[i],prev=i?World.gates[i-1]:{x:0,z:-900};let yaw=Math.atan2(g.x-prev.x,g.z-prev.z);engine.draw(world.ring,M.model([g.x,g.y,g.z],yaw,0,0,g.r),2,i===flight.gate?.85:.35)}
   if(flight.mode==='landing')for(let z=-4500;z<-750;z+=450)if(z>flight.p[2]+40){let h=46+Math.max(0,(-850-z))*.052;engine.draw(world.ring,M.model([0,h,z],0,0,0,flight.type!=='light'?56:30),2,.36)}
   if(flight.agl<550){let scale=flight.type!=='light'?19:6.5;let shadowModel=M.model([flight.p[0],World.ground(flight.p[0],flight.p[2])+.26,flight.p[2]],flight.yaw,0,0,scale);engine.draw(world.shadow,shadowModel,2,.23*Math.exp(-flight.agl/160))}
   drawPlane(flight.type,flight.p,flight.yaw,flight.pitch,flight.bank,app.view===1);
  }else{let p=app.preview;drawPlane(app.menuType,p.p,p.yaw,p.pitch,p.bank)}
  if(mission&&['descent','approach'].includes(mission.phase))for(let z=-20000;z<-1250;z+=650)if(z>flight.p[2]+40){let h=World.profile.elevation+flight.spec.gearHeight+(-1200-z)*.052;engine.draw(world.ring,M.model([0,h,z],0,0,0,54),2,.34)}if(mission&&mission.phase==='taxi'){let p=mission.taxiPoints[mission.taxiIndex];engine.draw(world.ring,M.model([p[0],World.profile.elevation+7,p[1]],0,0,0,10),2,.7)}
  drawHUD();
 }
 function project(p){let v=M.sub(p,cam.eye),z=M.dot(v,cam.f);if(z<.4)return null;let t=Math.tan(cam.fov/2);return [innerWidth/2+M.dot(v,cam.r)/z/t/cam.aspect*innerWidth/2,innerHeight/2-M.dot(v,cam.u)/z/t*innerHeight/2]}
 function drawHUD(){const W=innerWidth,H=innerHeight;hc.clearRect(0,0,W,H);if(!app.active)return;let labelY=[];for(let label of (World.labels||[])){let pt=project(label.p);if(pt){while(labelY.some(q=>Math.abs(q[0]-pt[0])<160&&Math.abs(q[1]-pt[1])<35))pt[1]-=36;labelY.push(pt.slice());}if(pt&&pt[0]>15&&pt[0]<W-15&&pt[1]>40&&pt[1]<H-120){hc.font='bold 12px sans-serif';hc.textAlign='center';hc.fillStyle='#dcffe4';hc.fillText(label.title,pt[0],pt[1]);hc.font='10px sans-serif';hc.fillText(label.sub,pt[0],pt[1]+16);hc.textAlign='left'}}
  if(app.view===1){let cx=W/2,cy=H*(H>W?.39:.43);hc.save();hc.beginPath();hc.rect(cx-125,cy-72,250,144);hc.clip();hc.translate(cx,cy);hc.rotate(-flight.bank);hc.translate(0,flight.pitch/DEG*2.7);hc.strokeStyle='rgba(215,244,227,.62)';hc.fillStyle='#e8f8ea';hc.lineWidth=1;hc.font='10px sans-serif';for(let a=-30;a<=30;a+=5){let y=-a*2.7,len=a%10===0?80:38;hc.beginPath();hc.moveTo(-len/2,y);hc.lineTo(len/2,y);hc.stroke();if(a&&a%10===0)hc.fillText(Math.abs(a),len/2+7,y+3)}hc.restore();hc.strokeStyle='#e4f3c4';hc.lineWidth=2;hc.beginPath();hc.moveTo(cx-36,cy);hc.lineTo(cx-10,cy);hc.lineTo(cx,cy+5);hc.lineTo(cx+10,cy);hc.lineTo(cx+36,cy);hc.stroke()}
  if(!flight.grounded&&flight.gs>5&&app.view!==2&&app.view!==3){let pos=project(M.add(flight.p,M.mul(M.norm(flight.v),700)));if(pos&&pos[0]>100&&pos[0]<W-100&&pos[1]>105&&pos[1]<H-165){hc.save();hc.strokeStyle='rgba(217,249,219,.76)';hc.lineWidth=1.5;hc.beginPath();hc.arc(pos[0],pos[1],5,0,Math.PI*2);hc.moveTo(pos[0]-14,pos[1]);hc.lineTo(pos[0]-5,pos[1]);hc.moveTo(pos[0]+5,pos[1]);hc.lineTo(pos[0]+14,pos[1]);hc.moveTo(pos[0],pos[1]-5);hc.lineTo(pos[0],pos[1]-12);hc.stroke();hc.restore()}}
  if(flight.mode==='lesson'&&flight.gate<World.gates.length){let g=World.gates[flight.gate],p=project([g.x,g.y+g.r*1.2,g.z]);if(p&&p[0]>20&&p[0]<W-20&&p[1]>45&&p[1]<H-190){hc.font='11px sans-serif';hc.fillStyle='#dcf5e2';hc.textAlign='center';hc.fillText((flight.gate+1)+' / 8 · '+g.name,p[0],p[1]);hc.textAlign='left'}}
  pc.setTransform(2,0,0,2,0,0);pc.clearRect(0,0,276,108);pc.fillStyle='#9ebbb8';pc.font='8px sans-serif';pc.textAlign='center';
  const x=56,y=50,r=38;pc.save();pc.beginPath();pc.arc(x,y,r,0,Math.PI*2);pc.clip();pc.translate(x,y);pc.rotate(-flight.bank);pc.translate(0,flight.pitch/DEG*1.35);pc.fillStyle='#377083';pc.fillRect(-110,-160,220,160);pc.fillStyle='#775c41';pc.fillRect(-110,0,220,160);pc.strokeStyle='#e3e8d6';pc.lineWidth=1;pc.beginPath();pc.moveTo(-100,0);pc.lineTo(100,0);pc.stroke();for(let a=-20;a<=20;a+=10)if(a){pc.beginPath();pc.moveTo(-12,-a*1.35);pc.lineTo(12,-a*1.35);pc.stroke()}pc.restore();pc.strokeStyle='#729797';pc.lineWidth=1;pc.beginPath();pc.arc(x,y,r,0,Math.PI*2);pc.stroke();pc.strokeStyle='#f1d391';pc.lineWidth=2;pc.beginPath();pc.moveTo(x-24,y);pc.lineTo(x-8,y);pc.lineTo(x,y+5);pc.lineTo(x+8,y);pc.lineTo(x+24,y);pc.stroke();pc.fillStyle='#a6bdb9';pc.fillText('ATTITUDE / 姿态',x,99);
  const nx=149,ny=49;pc.save();pc.translate(nx,ny);pc.strokeStyle='#64888b';pc.lineWidth=1;pc.beginPath();pc.arc(0,0,34,0,Math.PI*2);pc.stroke();pc.rotate(-flight.yaw-headingOffset());pc.fillStyle='#d8e8d9';pc.font='9px sans-serif';for(let i=0;i<12;i++){let a=i*Math.PI/6;pc.beginPath();pc.moveTo(Math.sin(a)*27,-Math.cos(a)*27);pc.lineTo(Math.sin(a)*31,-Math.cos(a)*31);pc.stroke()}for(let [s,a]of [['N',0],['E',Math.PI/2],['S',Math.PI],['W',-Math.PI/2]])pc.fillText(s,Math.sin(a)*23,-Math.cos(a)*23+3);pc.strokeStyle='#a6e3cd';let bearing=Math.atan2(-flight.p[0],-flight.p[2])+headingOffset();pc.rotate(bearing);pc.beginPath();pc.moveTo(0,-29);pc.lineTo(0,29);pc.moveTo(-4,-20);pc.lineTo(0,-29);pc.lineTo(4,-20);pc.stroke();pc.restore();pc.fillStyle='#efd69e';pc.beginPath();pc.moveTo(nx,ny-9);pc.lineTo(nx-5,ny+7);pc.lineTo(nx+5,ny+7);pc.closePath();pc.fill();pc.fillStyle='#a6bdb9';pc.fillText('NAV / 导航',nx,99);
  pc.strokeStyle='#729493';pc.lineWidth=.5;pc.beginPath();pc.moveTo(197,12);pc.lineTo(197,94);pc.stroke();pc.fillStyle='#9dbfba';pc.textAlign='left';pc.font='8px sans-serif';pc.fillText(flight.type!=='light'?'N1 / 双发':'RPM / 转速',209,20);pc.fillStyle='#c7eee0';pc.font='17px sans-serif';pc.fillText(flight.type!=='light'?Math.round((flight.engine?22:0)+flight.spool*76)+'%':Math.round((flight.engine?650:0)+flight.spool*2050).toString(),208,41);pc.fillStyle='#365951';pc.fillRect(209,48,50,4);pc.fillStyle='#a7dbc3';pc.fillRect(209,48,50*flight.spool,4);pc.font='8px sans-serif';pc.fillStyle='#91b6ae';pc.fillText('FUEL / 燃油',209,66);pc.fillStyle='#d8e9d7';pc.font='12px sans-serif';pc.fillText(flight.fuel.toFixed(0)+'%',209,82);pc.font='8px sans-serif';pc.fillStyle=flight.ap.on?'#a6e3cd':'#849d9c';pc.fillText(flight.ap.on?'AP · ALT HDG SPD':'MANUAL / 手动',207,99);pc.textAlign='center';
 }
 const text=(id,v)=>{if($(id).textContent!==String(v))$(id).textContent=v};
 function updateUI(){if(!app.active||!flight)return;let f=flight;const kt=f.ias*1.94384,vr=Math.round(f.spec.vr*1.94384),hdg=(f.yaw/DEG+360)%360;
  text('ias',Math.round(kt));text('alt',Math.round(f.p[1]*3.28084).toLocaleString('en-US'));text('vs',Math.round(f.v[1]*196.85/10)*10);text('hdg',String(Math.round(hdg)%360).padStart(3,'0'));text('gs','地速 '+Math.round(f.gs*1.94384)+' kt');text('agl','离地 '+Math.round(f.agl*3.28084)+' ft');text('load','载荷 '+(f.grounded?1:f.load).toFixed(1)+' G');text('navText',f.ap.on?'AP · 保持目标':'跑道 36 / 18');
  const power=Math.round(f.power*100);text('thrValue',power+'%');let height=$('throttle').clientHeight-20;$('thrFill').style.height=(f.power*height)+'px';$('thrHandle').style.bottom=(10+f.power*(height-12))+'px';$('throttle').setAttribute('aria-valuenow',power);$('flapsBtn').innerHTML='襟翼<b>'+f.flaps+' / 3</b>';$('gearBtn').innerHTML='起落架<b>'+(f.type==='light'?'固定式':Math.abs(f.gearActual-(f.gear?1:0))>.06?'移动中':f.gear?'已放下':'已收起')+'</b>';$('apBtn').innerHTML='自动驾驶<b>AP '+(f.ap.on?'开':'关')+'</b>';$('apBtn').classList.toggle('on',f.ap.on);$('flapsBtn').classList.toggle('on',f.flaps>0);text('flightBadge',(f.type==='a320'?'A320-216':f.type==='light'?'L-4':'J-120')+' / '+({free:'FREE FLIGHT',runway:'TAKEOFF',landing:'APPROACH',lesson:'ROUTE CHALLENGE'}[f.mode]||'BKI → CAN T3'));
  text('mapDist',(Math.hypot(f.p[0],f.p[2])/1852).toFixed(1)+' NM');text('footerInfo',({clear:'晴空无风',breeze:'侧风',turbulent:'轻度颠簸'}[f.weather])+' · '+['追尾','驾驶舱','翼侧','环绕'][app.view]+' · '+(f.assist?'稳定辅助':'手动气动')+' · '+Math.floor(f.t/60)+':'+String(Math.floor(f.t%60)).padStart(2,'0'));
  let hint='';if(f.touchdown)hint='已接地：'+(f.touchdown.sink*196.85).toFixed(0)+' ft/min。收油门，按住刹车减速至停止。';else if(f.grounded)hint=f.power<.7?'将右侧油门推高，沿跑道中线加速。':kt<vr?'滑跑加速中。约 '+vr+' kt 时，向下轻拉左摇杆。':'已到抬轮速度：向下轻拉，保持机头约 6–10°。';else if(f.mode==='lesson'&&f.gate<World.gates.length){let g=World.gates[f.gate];hint='航路点 '+(f.gate+1)+'/8 · '+g.name+' · 距离 '+Math.round(M.len(M.sub(f.p,[g.x,g.y,g.z])))+' m'}else if(f.mode==='landing')hint='36 跑道进近 · 参考 '+(f.type==='light'?'68':'144')+' kt。沿绿色引导圈下降；接地前轻拉杆减小下降率。';else if(f.t<30)hint='向下拉杆抬头，左右压杆转弯。轻推后松手；AP 可保持当前状态。';else if(f.ap.on)hint='自动驾驶 · '+Math.round(f.ap.alt*3.28084)+' ft / '+Math.round((f.ap.heading/DEG+360)%360)+'° / '+Math.round(f.ap.speed*1.94384)+' kt';else hint='自由飞行 · 点地图查看机场方向，点「系统」调整配平、天气与辅助。';text('instructor',mission?mission.hint(f):hint);if(mission){text('routePhase',mission.phaseName);$('routeFill').style.width=(mission.progress*100)+'%';text('guideBtn','教学领航：'+(mission.guide?'开':'关'));$('guideBtn').classList.toggle('on',mission.guide);text('routeStatus',(mission.progress*100).toFixed(0)+'% · '+(ROUTE_DATA.distance/1000).toFixed(0)+' km 大圆示意 · 分段体验');text('routeNext',({takeoff:'跳至巡航',climb:'跳至巡航',cruise:'跳至下降',descent:'跳至进近',approach:'重置进近'})[mission.phase]||'当前阶段');$('routeNext').disabled=['rollout','taxi','parked'].includes(mission.phase);text('navText',World.profile.runway);text('hdg',String(Math.round(((f.yaw/DEG+World.profile.heading)%360+360)%360)).padStart(3,'0'));document.querySelector('.map-label span').textContent=World.profile.name;}
  $('warning').classList.toggle('hidden',!f.warnings.length);text('warning',f.warnings.join(' / '));drawMap($('miniMap'));
 }
 function result(success){clearInputs();app.paused=true;let f=flight,td=f.touchdown;openModal('resultModal');text('resultEyebrow',success?'LANDING COMPLETE':'FLIGHT REPORT');text('resultTitle',success?'着陆完成':'本次飞行结束');text('resultNumber',success?td.score+' / 100':'重新练习');$('resultNumber').style.fontSize=success?'52px':'30px';text('resultReason',success?'飞机已在跑道停稳。分数根据接地下降率、坡度、航向与中心线偏差计算。':f.crashReason);$('resultStats').innerHTML='<div><small>飞行时间</small>'+Math.floor(f.t/60)+' 分 '+Math.floor(f.t%60)+' 秒</div><div><small>航程</small>'+(f.travel/1852).toFixed(1)+' NM</div>'+(success?'<div><small>接地下降率</small>'+Math.round(td.sink*196.85)+' FPM</div>':'');if(success)try{let key='cloudline.best.'+f.type;localStorage.setItem(key,Math.max(Number(localStorage.getItem(key)||0),td.score).toString())}catch(_){}
 }
 function events(){while(flight&&flight.events.length){let e=flight.events.shift();if(e.type==='notice')toast(e.text);if(e.type==='takeoff')toast('已经离地。保持小幅抬头，速度稳定后收襟翼。',3400);if(e.type==='gate')toast(e.index===World.gates.length?'航路点全部完成，请返回跑道降落。':'通过航路点 '+e.index+' / '+World.gates.length);if(e.type==='touchdown')toast('接地成功 · 收油门并按住刹车',3400);if(e.type==='landed'&&!mission)result(true);if(e.type==='parked'){result(true);text('resultTitle','BKI → CAN T3 完成');text('resultReason','已停入 SIM-T3 模拟机位。'+(mission.skips?'使用阶段跳转 '+mission.skips+' 次。':'')+'航路、机场布局与领航均为游戏化简化。');if(flight.touchdown&&flight.touchdown.practice)text('resultNumber','滑行完成');}if(e.type==='crash')result(false)}}
 let last=performance.now();function frame(now){const raw=Math.max(0,(now-last)/1000);last=now;const dt=Math.min(raw,.067);app.clock+=dt;app.fps=app.fps*.95+(1/Math.max(raw,.001))*.05;
  if(app.active&&!app.paused){accum+=dt;let steps=0;while(accum>=1/120&&steps<9){readInput(1/120);if(mission){let controls=mission.guideInput(flight,input,1/120);flight.step(1/120,controls);mission.afterStep(flight,1/120);if(mission.transfer)routeTransfer();}else flight.step(1/120,input);accum-=1/120;steps++;if(flight.crashed)break}events()}else accum=0;
  propAngle+=dt*(app.active?(flight.engine?20+flight.spool*130:0):90);render();if(now-app.lastUI>120){app.lastUI=now;updateUI();soundUpdate()}if(now>toastUntil)$('toast').classList.add('off');requestAnimationFrame(frame)
 }
 try{engine=new Engine(canvas);world=World.build(engine);models={light:buildAircraft(engine,'light'),jet:buildAircraft(engine,'jet'),a320:buildAircraft(engine,'a320')};navLights={red:engine.mesh(new Geometry().ellipsoid(0,0,0,.15,.12,.18,[1,.19,.12],6,3)),green:engine.mesh(new Geometry().ellipsoid(0,0,0,.15,.12,.18,[.13,1,.53],6,3)),white:engine.mesh(new Geometry().ellipsoid(0,0,0,.23,.16,.2,[1,.98,.86],6,3))};initMap();resize();$('startBtn').disabled=false;$('loading').classList.add('hidden');requestAnimationFrame(frame)}catch(e){fatal(e.message||String(e));console.error(e)}
 // Read-only getters plus explicit test actions, useful for local regression tests.
 window.__cloudline={get flight(){return flight},get mission(){return mission},routeTransfer,app,input,touch,get renderer(){return engine},get world(){return world},start,pause,resume,step(n,controls={}){for(let i=0;i<n;i++){if(mission){flight.step(1/120,mission.guideInput(flight,controls,1/120));mission.afterStep(flight,1/120);if(mission.transfer)routeTransfer();}else flight.step(1/120,controls);}events();updateUI()},version:'1.2.0'};
})();
