'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
vm.runInThisContext(['engine.js','world.js','routes.js','flight.js'].map(f=>fs.readFileSync(__dirname+'/'+f,'utf8')).join('\n'));
const results=[],mesh={mesh(g){return {count:g.data?.length||0}}};
function test(name,fn){try{const detail=fn();results.push({name,pass:true,detail});}catch(e){results.push({name,pass:false,error:e.message});}}
function setup(mode='bki_can'){AirportScenes.select('island');const f=new Flight('a320','runway'),r=new RouteMission(mode);r.configure(f,r.transfer);World.build(mesh);return {f,r};}
test('A320 model and approximate BKI-CAN great-circle distance',()=>{assert.equal(AIRCRAFT.a320.wing,122.6);assert(ROUTE_DATA.distance>1900000&&ROUTE_DATA.distance<2050000);return {km:ROUTE_DATA.distance/1000};});
test('BKI and CAN scene boundaries are separate',()=>{let {f,r}=setup();assert.equal(World.scene,'bki');assert(World.runway(0,1800));assert(!World.runway(30,0));r.configure(f,'approach');World.build(mesh);assert.equal(World.scene,'can');assert.equal(World.profile.elevation,15);assert(World.labels.some(l=>l.title==='SIM-T3'));assert(World.obstacles.length>=4);});
test('Manual input cancels demonstration guidance',()=>{let {f,r}=setup();r.guide=true;const input=r.guideInput(f,{pitch:.6},1/120);assert(!r.guide);assert.equal(input.pitch,.6);});
test('Explicit scene skips increment counter without finishing mission',()=>{let {f,r}=setup();assert(r.requestNext(f));r.configure(f,r.transfer);assert.equal(r.phase,'cruise');assert.equal(r.skips,1);assert(!r.finished);assert(f.p[1]>10000);});
test('Cruise transfer survives floating-point boundary',()=>{let {f,r}=setup();r.configure(f,'cruise');r.cruiseDistance=ROUTE_DATA.distance*.82; r.afterStep(f,1/120);assert.equal(r.transfer,'descent');});
test('Cruise local-origin rebase preserves finite flight state',()=>{let {f,r}=setup();r.configure(f,'cruise');f.p[2]=10000;r.afterStep(f,1/120);assert.equal(f.p[2],0);assert(f.p.every(Number.isFinite));});
test('Taxi apron is paved and building is collidable',()=>{let {f,r}=setup('can_taxi');assert(World.paved(115,-440));assert(World.paved(245,-440));assert(!World.paved(700,-440));f.p=[500,18.9,-440];f.v=[0,0,1];f.step(1/120,{});assert(f.crashed);});
test('Cannot complete T3 parking while moving',()=>{let {f,r}=setup('can_taxi');f.p=[245,18.9,-440];f.gs=4;f.power=0;f.lastBrake=true;r.afterStep(f,1/120);assert(!r.finished);f.gs=0;r.afterStep(f,1/120);assert(r.finished);});
for(const mode of ['bki_can','can_approach','can_taxi'])test(mode+' guidance reaches T3 with scenery collisions enabled',()=>{let {f,r}=setup(mode);r.guide=true;const phases=[];let last='';for(let i=0;i<120*1700;i++){f.step(1/120,r.guideInput(f,{},1/120));r.afterStep(f,1/120);if(r.transfer){r.configure(f,r.transfer);World.build(mesh);}if(r.phase!==last){phases.push(r.phase);last=r.phase;}if(f.crashed||r.finished)break;}assert(!f.crashed,f.crashReason);assert(r.finished,'did not reach parking');assert.equal(r.phase,'parked');assert(Math.hypot(f.p[0]-245,f.p[2]+440)<12);assert(f.gs<1);if(mode==='bki_can')for(const p of ['takeoff','climb','cruise','descent','approach','rollout','taxi','parked'])assert(phases.includes(p),p);return {simulationSeconds:Math.round(f.t),phases,position:f.p,landingScore:f.touchdown?.score};});
const report={version:'1.2.0',suite:'route physics at 120 Hz, deterministic calm-weather scenarios; no real-world flight validation',passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length,results};
fs.writeFileSync(__dirname+'/route_test_results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.failed)process.exit(1);
